<template>
  <div class="absolute inset-0 overflow-y-auto bg-base">
    <div class="max-w-2xl mx-auto px-6 py-12">
      <NuxtLink
        to="/"
        class="inline-flex items-center gap-2 text-dim hover:text-body text-xs transition-colors mb-10"
      >
        <UIcon name="i-lucide-arrow-left" class="w-3 h-3" />
        Back to app
      </NuxtLink>

      <h1 class="text-2xl font-semibold text-white mb-1">Terms of Use</h1>
      <p class="text-dim text-xs mb-10">
        Cutlist Generator &mdash; v{{ appConfig.version }}
      </p>

      <section class="space-y-8 text-sm text-body leading-relaxed">
        <div>
          <h2
            class="text-teal-400 text-xs font-semibold uppercase tracking-wider mb-3"
          >
            Beta Software
          </h2>
          <p>
            Cutlist Generator is currently offered as a
            <strong class="text-white">free beta product</strong>. It is under
            active development. Features may change, break, or be removed
            without notice. Data stored in your browser (IndexedDB) may be lost
            during updates. Export your projects regularly.
          </p>
        </div>

        <div>
          <h2
            class="text-teal-400 text-xs font-semibold uppercase tracking-wider mb-3"
          >
            No Warranty
          </h2>
          <p>
            This software is provided
            <strong class="text-white">"as is"</strong>, without warranty of any
            kind, express or implied, including but not limited to warranties of
            merchantability, fitness for a particular purpose, or
            non-infringement. Cutting plans generated by this tool are estimates
            only. Always verify measurements before cutting material.
          </p>
        </div>

        <div>
          <h2
            class="text-teal-400 text-xs font-semibold uppercase tracking-wider mb-3"
          >
            Limitation of Liability
          </h2>
          <p>
            In no event shall the author be liable for any claim, damages, or
            other liability arising from the use of this software, including but
            not limited to material waste, incorrect cuts, or data loss. Use at
            your own risk.
          </p>
        </div>

        <div>
          <h2
            class="text-teal-400 text-xs font-semibold uppercase tracking-wider mb-3"
          >
            Privacy
          </h2>
          <p>
            All data (projects, models, settings) is stored locally in your
            browser. Nothing is transmitted to any server. No analytics,
            cookies, or tracking of any kind.
          </p>
        </div>

        <div>
          <h2
            class="text-teal-400 text-xs font-semibold uppercase tracking-wider mb-3"
          >
            Open Source Software
          </h2>
          <p class="mb-4">
            Cutlist Generator is built on the following open source libraries.
            Each is used under its respective license.
          </p>
          <table class="w-full text-xs border-collapse">
            <thead>
              <tr class="border-b border-subtle">
                <th class="text-left text-dim font-normal pb-2 pr-6">
                  Package
                </th>
                <th class="text-left text-dim font-normal pb-2 pr-6">
                  Version
                </th>
                <th class="text-left text-dim font-normal pb-2">License</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-mist-900">
              <tr v-for="dep in deps" :key="dep.name" class="hover:bg-surface">
                <td class="py-2 pr-6 text-body">{{ dep.name }}</td>
                <td class="py-2 pr-6 text-dim">{{ dep.version }}</td>
                <td class="py-2 text-dim">{{ dep.license }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <p class="mt-12 text-dim text-xs">
        Built by Matt &mdash; {{ new Date().getFullYear() }}
      </p>
    </div>
  </div>
</template>

<script lang="ts" setup>
const appConfig = useAppConfig();

const deps = [
  { name: 'Nuxt', version: '4', license: 'MIT' },
  { name: 'Vue', version: '3', license: 'MIT' },
  { name: 'Nuxt UI', version: '3', license: 'MIT' },
  { name: 'VueUse', version: '14', license: 'MIT' },
  { name: 'Three.js', version: '0.184', license: 'MIT' },
  { name: 'pdf-lib', version: '1.17', license: 'MIT' },
  { name: 'idb', version: '8', license: 'ISC' },
  { name: 'js-yaml', version: '4', license: 'MIT' },
  { name: 'Zod', version: '4', license: 'MIT' },
  { name: 'Tailwind CSS', version: '4', license: 'MIT' },
  { name: 'Lucide Icons', version: '1', license: 'ISC' },
];

useHead({ title: 'Terms of Use — Cutlist Generator' });
</script>
